# Configuração Limpa - Ian Araújo
locale: "pt-BR"
site_theme: "default"
title: "Ian Araújo | Portfólio"
title_separator: "-"
name: "Ian Araújo"
description: "Estudante de Engenharia Elétrica - UFSJ"
url: "https://ianaraujof.github.io"
baseurl: ""
repository: "ianaraujof/ianaraujof.github.io"

author:
  avatar: "perfil.jpg"
  name: "Ian Araújo Figueiredo"
  bio: "Estudante de Engenharia Elétrica na UFSJ. Entusiasta em projetos elétricos e automação."
  location: "São João Del-Rei, MG"
  email: "ianfigueiredo6@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ianaraujof"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ian-araujo-b6111b260/"

include:
  - .htaccess
  - _pages
  - files
exclude:
  - node_modules
  - package.json
  - LICENSE
  - README
  - tmp
  - vendor

markdown: kramdown
highlighter: rouge

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
