# Welcome to Jekyll!
locale: "en-US"
site_theme: "default"
title: "Academic Pages"
title_separator: "-"
name: &name "Your Name"
description: &description "personal description"
url: # https://[your GitHub username].github.io
baseurl: ""
repository: # [your GitHub username]/[your GitHub username].github.io
author:
  avatar: "bio-photo.jpg"
  name: "Your Name"
  bio: "Your bio goes here."
  location: "City, Country"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:your-email@example.com"
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - node_modules
  - package.json
  - LICENSE
  - README
  - tmp
  - vendor
markdown: kramdown
highlighter: rouge
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true
